<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ws_products"
 *
 * Auto generated by Extension Builder 2015-05-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'WS Products',
	'description' => 'Product Management with multiple Filter possibility',
	'category' => 'plugin',
	'author' => 'Daniel Klessa',
	'author_email' => 'info@webschuppen.com',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 1,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0 - 7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);